name: benchmarks
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
env:
  FORCE_COLOR: '1'
  PY_COLORS: '1'
jobs:
  bench:
    name: run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: pyproject.toml
          enable-cache: true
      - run: uv pip install '.[tests]' --system
      - id: measurement-5
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: run benchmarks on base branch
        run: pytest --benchmark-autosave dvc/testing/benchmarks/ -k 'test_init or
          test_help'
      - id: measurement-7
        name: Record Measurement After run benchmarks on base branch
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: run benchmarks on base branch
          task: get-measurement
      - uses: actions/checkout@v5
        with:
          clean: false
          fetch-depth: 0
      - run: uv pip install '.[tests]' --system
      - id: measurement-10
        name: Record Measurement After Step
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Step
          task: get-measurement
      - name: run benchmarks for PR
        run: 'pytest --benchmark-compare --benchmark-compare-fail=min:5% --benchmark-group-by
          name dvc/testing/benchmarks/ -k ''test_init or test_help''

          '
      - id: measurement-12
        name: Record Measurement After run benchmarks for PR
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: run benchmarks for PR
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
