name: Remote Plugin Tests
on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: start-measurement
      - uses: actions/checkout@v5
        with:
          path: dvc
      - uses: actions/checkout@v5
        with:
          path: ${{ matrix.plugin }}
          ref: main
          repository: iterative/${{ matrix.plugin }}
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.pyv }}
      - uses: astral-sh/setup-uv@v7
        with:
          cache-dependency-glob: '**/pyproject.toml'
          cache-suffix: ${{ matrix.pyv }}
          enable-cache: true
      - name: Install plugin + DVC@PR
        run: 'uv pip install "./dvc[testing]" --system

          uv pip install -e "./${{ matrix.plugin }}[tests]" --system

          '
      - id: measurement-6
        name: Record Measurement After Install plugin + DVC@PR
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Install plugin + DVC@PR
          task: get-measurement
      - name: Run plugin tests
        run: pytest -v -n=auto
        timeout-minutes: 15
        working-directory: ${{ matrix.plugin }}
      - id: measurement-8
        name: Record Measurement After Run plugin tests
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          label: Run plugin tests
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@862050e4f01f65b1436e5eca18ba4bd85562f0de
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        plugin:
          - dvc-s3
        pyv:
          - '3.14'
    timeout-minutes: 45
permissions:
  contents: read
